package com.example.studysmart.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF256C22)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA9F59A)
val md_theme_light_onPrimaryContainer = Color(0xFF002201)
val md_theme_light_secondary = Color(0xFF2F6C03)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFAFF583)
val md_theme_light_onSecondaryContainer = Color(0xFF092100)
val md_theme_light_tertiary = Color(0xFF885200)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDBB)
val md_theme_light_onTertiaryContainer = Color(0xFF2B1700)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF251A00)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF251A00)
val md_theme_light_surfaceVariant = Color(0xFFDFE4D8)
val md_theme_light_onSurfaceVariant = Color(0xFF42493F)
val md_theme_light_outline = Color(0xFF73796E)
val md_theme_light_inverseOnSurface = Color(0xFFFFEFD3)
val md_theme_light_inverseSurface = Color(0xFF3F2E00)
val md_theme_light_inversePrimary = Color(0xFF8ED980)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF256C22)
val md_theme_light_outlineVariant = Color(0xFFC2C8BC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF8ED980)
val md_theme_dark_onPrimary = Color(0xFF003A04)
val md_theme_dark_primaryContainer = Color(0xFF04530A)
val md_theme_dark_onPrimaryContainer = Color(0xFFA9F59A)
val md_theme_dark_secondary = Color(0xFF94D96A)
val md_theme_dark_onSecondary = Color(0xFF143800)
val md_theme_dark_secondaryContainer = Color(0xFF215100)
val md_theme_dark_onSecondaryContainer = Color(0xFFAFF583)
val md_theme_dark_tertiary = Color(0xFFFFB868)
val md_theme_dark_onTertiary = Color(0xFF482900)
val md_theme_dark_tertiaryContainer = Color(0xFF673D00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDBB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF251A00)
val md_theme_dark_onBackground = Color(0xFFFFDF9C)
val md_theme_dark_surface = Color(0xFF251A00)
val md_theme_dark_onSurface = Color(0xFFFFDF9C)
val md_theme_dark_surfaceVariant = Color(0xFF42493F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C8BC)
val md_theme_dark_outline = Color(0xFF8C9388)
val md_theme_dark_inverseOnSurface = Color(0xFF251A00)
val md_theme_dark_inverseSurface = Color(0xFFFFDF9C)
val md_theme_dark_inversePrimary = Color(0xFF256C22)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF8ED980)
val md_theme_dark_outlineVariant = Color(0xFF42493F)
val md_theme_dark_scrim = Color(0xFF000000)


val Red = Color(0xFFD53A2F)
val Blue = Color(0xFF2965C9)
val Green = Color(0xFF1E9651)
val Orange = Color(0xFFFF9800)

val gradient0 = listOf(Color(0xFFad5389),Color(0xFF3C1053))
val gradient1 = listOf(Color(0xFF3A6073),Color(0xFF16222A))
val gradient2 = listOf(Color(0xFFF857A6),Color(0xFFFF5858))
val gradient3 = listOf(Color(0xFF00D2FF),Color(0xFF3A7BD5))
val gradient4 = listOf(Color(0xFF99F2C8),Color(0xFF1F4037))